### ISSUE TITLE
Abnormal code block display 

### ISSUE THREAD

**Issue by HUGHNew** [TEParsons/torillic#5]
![the-look](https://user-images.githubusercontent.com/52786639/118161340-08a0b580-b452-11eb-99c5-26cf7af383d3.png)
This is how this theme display

Some unexpected things occur  while I'm writing the code snippet

A nice theme it is without the little bug.

The source code is as follows

## System

1.  PowerShell
    1.  `$env:OS`:Windows_NT
2.  Linux
    1.  `$OSTYPE`:linux-gnu

```bash
ifeq ($(OSTYPE),linux-gnu)
	# todo
else ifeq ($(env:OS).Windows_NT)
	# todo
endif
```

## Rule

```makefile
target ... : prerequisites ...
    command
    ...
    ...
```

**Comment by TEParsons** [comment]
Could you attach the .md which was breaking this for you? When I try copying the text you included it looks fine:
![image](https://user-images.githubusercontent.com/25686106/118979382-4fba0980-b970-11eb-81cd-d2f3b8d9db3c.png)

**Comment by HUGHNew** [comment]
![image](https://user-images.githubusercontent.com/52786639/119008003-55413f00-b9c4-11eb-81a2-a6e28837fe8a.png)

This is how it displayed

And here is the the file
[test.md](https://github.com/TEParsons/torillic/files/6517138/test.md)

Something weird is the other themes works.

I guess that the UTF8 Char causes this problem

However, it didn't matter

**Comment by TEParsons** [comment]
Still looks fine when I open the file, very strange... Only thing I can think is if there's a difference between your `base.css` and mine which interacts with something in Torillic? Very difficult to debug this without being able to replicate the bug.

**Comment by HUGHNew** [comment]
Err... Problem remains after I pasted the code again
Hard to debug and  I give up
Thanks a lot
