### ISSUE TITLE
Suggestions for improving the default color of the sidebar font （侧边栏字体默认颜色的一些改善建议）

### ISSUE THREAD

**Issue by GamesSoul** [TEParsons/torillic#7]
![图片](https://user-images.githubusercontent.com/37973776/138992561-54052433-3db5-4f91-8f12-57b9d58d4b8f.png)
It is recommended to set the default color of the text to be slightly brighter, otherwise it will overlap with the background and make it difficult to see （建议把文字默认颜色设置稍亮一些，否则会跟背景叠加从而让人看不清楚）

color: #dfe6e9

**Comment by TEParsons** [comment]
Fixed in v2.0, as sidebar now no longer inherits the body background
