### ISSUE TITLE
The exported PDF file is missing content

### ISSUE THREAD

**Issue by AptX395** [TEParsons/torillic#8]
Hello, the theme you developed is very beautiful, especially its double-column layout! Thank you very much for your work!

Unfortunately, when I tried to export a PDF file under your theme, I found that a lot of content was missing in the file.

Specifically, only all the first-level headings and the content under the first first-level heading are retained, and all the content under the other first-level headings are lost.

Do you know the cause of this problem? How can I export the PDF file correctly?

**Comment by TEParsons** [comment]
Fixed [here](https://github.com/TEParsons/torillic/commit/deca69d5c4f60da1a0589939a3a173529914e2a7)
