### ISSUE TITLE
When typing the cursor and entered text gets centered on the page.

### ISSUE THREAD

**Issue by THERockyH** [TEParsons/torillic#9]
Hey, I love the theme and plan on using it for some RPG stuff I'm writing. 
However, When typing the cursor and entered text gets centered on the page, and then once you click out of the area, the text is left-aligned like you'd expect. While the text ends up ok in basic paragraphs, it makes it hard to edit and see where things are going. 
You can see the starting line is inserted in the center of the page. 
![image](https://user-images.githubusercontent.com/1853594/160542628-6d7c2062-4104-41c5-b437-aa466ace616a.png)

Once you select somewhere else, it snaps to left-justified
![image](https://user-images.githubusercontent.com/1853594/160542711-ef6bdd43-7e43-43ed-98c1-4d9d8016731c.png)

**Comment by TEParsons** [comment]
Unfortunately, I think this behaviour is just how CSS handles columns - when you've got barely any content, it will start off in the second column. If anyone who knows more about CSS than I do knows a way around it, please feel free to reopen this issue & then put in a pull request to fix it!
